---
abstract: 'A RRDtool command wrapper with rawish interface'
author:
  - 'Yuuki Tsubouchi  C<< <yuuki@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Fatal: 0
  Test::Mock::ExternalCommand: 0
  Test::More: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.5.3, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RRDTool-Rawish
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  RRDTool::Rawish:
    file: lib/RRDTool/Rawish.pm
    version: 0.032
requires:
  Capture::Tiny: 0
  File::Which: 1.09
  perl: 5.008
resources:
  bugtracker: https://github.com/y-uuki/p5-RRD-Rawish/issues
  homepage: https://github.com/y-uuki/p5-RRD-Rawish
  repository: git://github.com/y-uuki/p5-RRD-Rawish.git
version: 0.032
x_contributors:
  - 'y_uuki <yuki.tsubo@gmail.com>'
